import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import Image from "next/image";
import localFont from "@next/font/local";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { IconProp } from "@fortawesome/fontawesome-svg-core";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faMobileAndroidAlt } from "@fortawesome/free-solid-svg-icons";
import Header from "./header";
import { MainContent } from "./maincontent";



const blenderpro = localFont({
  src: [
    {
      path: "../../public/fonts/blenderpro/BlenderPro-Medium.woff",
      weight: "400",
    },
  ],

  variable: "--font-blenderpro",
  display: "swap"
});

const iconsfont = localFont({
  src: [
    {
      path: "../../public/fonts/icons/icons.woff",
      weight: "400",
    },
  ],

  variable: "--font-icons",
  display: "swap"
});

export const metadata: Metadata = {
  title: "Offroadmotto | Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`_webp ${blenderpro.className}`}>
        <div className="wrapper _loaded">
         <Header />
         <MainContent>{children}</MainContent>
        </div>
      </body>
    </html>
  );
}
